### ISSUE TITLE
bidsCopyRawFolder tells that tsv are copied when there are no tsv files in the raw folder

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_SPM#264] opened 2021-01-13 15:13 UTC
## Describe your problem in detail

running `bidsCopyRawFolder` and no tsv in the `raw` folder, the func print:

```
copying subject: sub-pilot001 
 copying session: ses-003 
 tsv files copied
 json files copied
```

## Describe what outcome you expected 

that it tells `no tsv files found` (either as warning or error)

## Describe what you got instead

```
copying subject: sub-pilot001 
 copying session: ses-003 
 tsv files copied
 json files copied
```

without any complain

### Error message

No error message

**Comment by Remi-Gau** [comment] 2021-01-13 15:18
but... it should not do that... 

Grmf...

https://github.com/cpp-lln-lab/CPP_SPM/blob/7a77e637c98b152f893a5a78a84d49f9d5566d6d/src/workflows/bidsCopyRawFolder.m#L162

**Comment by Remi-Gau** [comment] 2021-01-13 15:19
there is no `scans.tsv` file?

**Comment by marcobarilari** [comment] 2021-01-13 15:25
You are right, there are two `tsv` files (participants and scans), stupid Marco.

I don't know if this issue is still informative though if we want to implement a `waring` message in case no `event` files are in the raw folder. Otherwise, we close it right away.

**Comment by Remi-Gau** [comment] 2021-01-13 15:34
> You are right, there are two tsv files (participants and scans), stupid Marco.

Nope. Good to cross-check. I did spend half of the day wondering why a github action for some tests was telling some dummy data was not there only to realize that I had never "pushed" the data... Computers are seldom wrong: who knew?

No tsv or json in the session folder is OK.

No json in the root folder should be worrying because it means it is not a BIDS data set. 

bids-matlab layout function does a bare minimum check: https://github.com/bids-standard/bids-matlab/blob/9f9296fb076c916477cfa3d0eef42612685a5a73/%2Bbids/layout.m#L64

I am OK having more stringent checks but the problem is that only the dataset description json is required by BIDS in the root folder. 
So we could throw "some" warnings but no error.

Once again a lot of the things here assumes that people have used the validator to make sure their data is OK

So we could leave it open and feel free to open a PR: though I suspect this is low priority.

**Comment by marcobarilari** [comment] 2021-01-17 22:03
Yes you are right, good for me to stick with BIDS rules in order to decide what could an error here.

**Comment by Remi-Gau** [comment] 2021-06-14 13:40
closing as this will be rendered obsolete in #367

**Closed by Remi-Gau** 2021-06-14 13:40 UTC
Labels: bug
